### ISSUE TITLE
PHP Deprecated

### ISSUE THREAD

**Issue by Justman100** [librewiki/liberty-skin#29]
Get this:

> PHP message: PHP Deprecated:  Use of ContentHandler::getContentText was deprecated in MediaWiki 1.37. [Called from LibertyTemplate::parseNavbar in skins/liberty-skin/LibertyTemplate.php:879]

**Comment by Justman100** [comment]
@Hoto-Cocoa

**Comment by Hoto-Cocoa** [comment]
Why you mentioned me suddenly at all opened issues?

**Comment by Justman100** [comment]
> Why you mentioned me suddenly at all opened issues?

To make sure that you are notified of these

**Comment by mary-kate** [comment]
I've submitted pull request #32 to address this; if no-one else merges it sooner, I'll do that by Christmas or so.

In any case, E_DEPRECATED is mostly just logspam for developers and nothing to really worry about, since after all, even in current master `ContentHandler#getContentText` remains present and usable (and it spams the logs just as heavily as in previous versions of MediaWiki). The log spam is basically the reason why _don't_ have logging enabled for these kind of things in production. ;-)

**Comment by Hoto-Cocoa** [comment]
I merged it - this issue should resolved now.
